version: "3.4"

services:
#--------------------------------------------------------------------------------------------------
# Apache + PHP
  webserver:
    build: 
      context: ./containers/${PHP_FOLDER}
    container_name: "${PROJECT_BASENAME}-${PHP_FOLDER}"
    restart: "always"
    ports:
      - "${HOST_MACHINE_HTTP_PORT}:80"
      - "${HOST_MACHINE_HTTPS_PORT}:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./data/www/html}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts/}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
#--------------------------------------------------------------------------------------------------
# MariaDB database
  mysql:
    build:
      context: "./containers/${MARIADB_FOLDER}"
    container_name: "${PROJECT_BASENAME}-${MARIADB_FOLDER}"
    restart: "always"
    ports:
      - "127.0.0.1:${HOST_MACHINE_MARIADB_PORT}:3306"
    volumes: 
      - ${MARIADB_DATA_DIR-./data/mariadb}:/var/lib/mariadb
      - ${MARIADB_LOG_DIR-./logs/mariadb}:/var/log/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
#--------------------------------------------------------------------------------------------------
# PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "${PROJECT_BASENAME}-phpmyadmin"
    restart: "always"
    environment:
      PMA_HOST: ${PMA_HOST}
      # PMA_PORT: ${PMA_PORT}
      # PMA_USER: ${PMA_USER}
      # PMA_PASSWORD: ${PMA_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${PMA_SUPER_PASSWORD}
      # MYSQL_USER: ${PMA_SUPER_USER}
      # MYSQL_PASSWORD: ${PMA_SUPER_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - "${HOST_MACHINE_PMA_PORT}:8080"
    # links:
    #   - mysql
    # volumes:
    #   - /sessions
    #   - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
