version: "3.1"

services:
#--------------------------------------------------------------------------------------------------
# Apache + PHP
  webserver:
    build: 
      context: ./containers/${PHPVERSION}
    container_name: '${PROJECT_BASENAME}-${PHPVERSION}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_HTTP_PORT}:80"
      - "${HOST_MACHINE_HTTPS_PORT}:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}

#--------------------------------------------------------------------------------------------------
# Mysql database
  mysql:
    build:
      context: "./containers/${MYSQL_FOLDER}"
      container_name: '${PROJECT_BASENAME}-mysql'
      restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

